version: "3.9"
services:
  # backend:
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile-dev
  #   restart: always
  #   ports:
  #     - 8001:8001
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres
    ports:
      - 54322:5432
    volumes:
      - ./db_posgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_go

  # profile:
  #   build:
  #     context: ./profile
  #     dockerfile: ./profile.service.Dockerfile
  #   restart: always
  #   ports:
  #     - 8002:8002
  #   volumes:
  #     - ./profile:/app
  #   depends_on:
  #     - postgres
